ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [com.tequipy.weather.ApplicationKt.module]
    }
}

weather {
    upstream {
        baseUrl = "https://api.open-meteo.com"
        baseUrl = ${?UPSTREAM_BASE_URL}
        timeoutMs = 1000
        timeoutMs = ${?UPSTREAM_TIMEOUT_MS}
    }
    cache {
        ttlSeconds = 60
        ttlSeconds = ${?CACHE_TTL_SECONDS}
        maxSize = 1000
        maxSize = ${?CACHE_MAX_SIZE}
    }
}
